sudo: false


language: c


cache:
  directories:
  - "$HOME/.stack"


os:
  - linux
  - osx


addons:
  apt:
    packages:
    - libgmp3-dev


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-tar; fi
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      travis_retry curl -L "https://www.stackage.org/stack/osx-x86_64" | gtar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
   - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      travis_retry curl -L "https://www.stackage.org/stack/linux-x86_64" | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    fi
  - stack --version


install:
  - stack setup
  - stack build --only-dependencies


script:
  - stack build


before_deploy:
   - tar zcvf "${TRAVIS_OS_NAME}.tar.gz" $(stack path --local-install-root)/bin/elm-instrument 


deploy:
  provider: releases
  api_key:
    secure: ZMf3BRr91zTYRKiZArCBJ9lyJG2W33LKM25tlvSpMDi2kBSUqvpYyRnZKiod1eQJ8O2Av8bRPE2fc4stJMfRxsqVE0U5G1I6Md9UDPVxSAYq1Jfr9yTqIfHEOY+P9ePFo2wOqsMEqpWppkaSuE2WcW61YtN32GeXaizuOKE1Fz+j6wY8HvOcAH9Rf29SI8wZhCTp8tTxvQkYy9ICpbZMWZNaJVrsmHpO7Ob0Yy5Y93QQGnvgPrSGkYu0p0hgec45LGh1UucKb0i/D6to8+Fun2Md4Z08DoBJf8bOnJjNtDv06vviq13x20mm0/zcBELy/PkpducgqWtvZ+inJ4+xcEGTn1qD968EfhqAijpcXfLDHLpQ5ooss7XTDb2sWcdmC5eE/dzCkUE0KUnIPJjxy/XEPHX8xrhsHueng0PzoeN7Iom3ZLOqEwcl6L6WldULasSOf/Cl/t8Yy+zYpVLJI91qz6RRhWAbRsTgDuM9yyMlwZmiv2WaalXDzLP8NqHZItmW7WngYb0hVFD0w/ly4pTsK+0VJ9HlCJD8RM7bESgrj61YNdrkLTwG+UkumIpCbgvDnmP6nTus86a5T2k4bgBIT2kA77xi4bUHJbF0ba3JiaK0ZZ5OzckH/b7zHlpsqAR+S5eeEnWiUvXH/THRELAE/JYjjbGFYUEEPQIf0/Y=
  skip_cleanup: true
  file: "${TRAVIS_OS_NAME}.tar.gz"
  name: $(git describe --abbrev=8 --always)
  draft: true
  on:
    repo: zwilias/elm-instrument
