sudo: false


language: c


cache:
  directories:
  - "$HOME/.stack"


os:
  - linux
  - osx


addons:
  apt:
    packages:
    - libgmp3-dev


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-tar; fi
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      travis_retry curl -L "https://www.stackage.org/stack/osx-x86_64" | gtar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      travis_retry curl -L "https://www.stackage.org/stack/linux-x86_64" | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
    fi
  - stack --version


install:
  - stack setup
  - stack build --only-dependencies


script:
  - stack build


before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then strip $(stack path --local-install-root)/bin/elm-instrument; fi
  - tar zcvf "${TRAVIS_OS_NAME}-x64.tar.gz" -C $(stack path --local-install-root)/bin elm-instrument


deploy:
  provider: releases
  api_key:
    secure: WpH0YFrIM6/x+MHoyTPJXeE7o0zMLC5VTSbyfi+SitDMQr4/lId4c9mtO2L89ST4yJPTzbkhJP7lgogsO+l0DIQ+XT8gcENM1Ma7VOoFpIjihBmYIWmOKQNawrNPnpXM/OmfCeNlh6UYTzRubLcxSOjiuItf3NWNIkU8EIbwDa+kk5jvTgBvHW6ibJ6d84ZWhSIaul2SB1nInso0YMs4esauITdvUcBZSdSQUoZtCPwi4LrffNiqO2NI4Wk5TgtQKfCZUPTl2aFKTiqD+5kxgYfvkET1gcWX7LHouW+b2sWf4hEBVS6FVJABX2AXG4eyuL+UBDKf4RgZmceCqAs10+iOEikjK1KQdhGSbPu4bPm6aU1BlUPkev4Dn3ngWXlaxB8flT3qGk8lKdYIX55UfONc8pfnBGk1C4Udn+FRfAD9LwuQoZljGR2jNs5V1NlpMABlP4J2oXhS9BBjttOz2Iz0JwFxULIjul6azzbz93DnWITtq6BcsKakiPVjpwVso7fCiCZiZJM53bflsQ41Av5Xpav21jfVOfg842bYe2kipBBPjpHiXf1eoZBPKKgE2/qBaQWFBchFkPuGzNnzrBEITJkNtU1Tb/h/wBvN0Lmtq/P9ZhA81l/zTNF+3PaHuhgE4T+8fG+x68FHdEuUyWyhFWzmCNxmkoia7BhcPJk=
  skip_cleanup: true
  file: "${TRAVIS_OS_NAME}-x64.tar.gz"
  draft: true
  name: elm-instrument $TRAVIS_TAG
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  on:
    repo: zwilias/elm-instrument
    tags: true
