sudo: false


language: c


cache:
  directories:
  - "$HOME/.stack"


os:
  - linux
  - osx


addons:
  apt:
    packages:
    - libgmp3-dev


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gnu-tar; fi
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      travis_retry curl -L "https://www.stackage.org/stack/osx-x86_64" | gtar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
      travis_retry curl -L "https://www.stackage.org/stack/linux-x86_64" | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
    fi
  - stack --version


install:
  - stack setup
  - stack build --only-dependencies


script:
  - stack build


before_deploy:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then strip $(stack path --local-install-root)/bin/elm-instrument; fi
  - tar zcvf "${TRAVIS_OS_NAME}-x64.tar.gz" -C $(stack path --local-install-root)/bin elm-instrument


deploy:
  provider: releases
  api_key:
    secure: "sf8lmmD17OXKiMvQSTs/eB6vkNbslkwohBdjvqvYbJuyCpGEjx/W0AVrOVvAQ0YEwhapUmTuTkZ5t37A2NWhN5PWjZmFpsdoITCPAPSqlisZad7Kqa8+gDA+o6DM6vx+ugx4LhdOpfr+6h47GQ9dPUqCaMcf9GAXsy+Xufj3T5IpagV9a/un7IAuOTSTmmPbSS4/LVmd7m/S4Ymnsl11A4iBiCOiJSMXWpPoeBzhwgr4RaAbG8svyXZ9m7TGkLkGtKnTJE9JkeRmNKzDxM3+hhWqv0ZT6/G1Dxb3F5OfISp7RQHyioovEgcSCMTDRfh7PBO5RPQhDS6uwqQthMVQW7lraKH13ocxNLVe0jHpqUippn0W0Eus30pLQJf/g2S6prKAA3ms6QQf698rQUDtN8VDBU/WE2wuhL6z047NZOJHYDLfUkvh5MnATHgpl+DcI376GgePxfFjBqbCymm/rCzcHFR+JbGyExiF1oPRBEID953oQ5bwBl8VTx6zyHy1Bef3bT11/9RGiM+0SRnYIaB6OfK2vf2kX3rAqChZEdNZHnRVOID46dT1R4rloTkhjpzZpswRZv5L1CaebTCCnuGolTxb4rj5OI7Uhmo2hP7TXELyak6mU5rZH1pbVQuL3BatDICm67XgT2mPdqaSmFwAOL2PhMB5JMY6NAXqsGE="
  skip_cleanup: true
  file: "${TRAVIS_OS_NAME}-x64.tar.gz"
  draft: true
  name: elm-instrument $TRAVIS_TAG
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  on:
    repo: zwilias/elm-instrument
    tags: true
