build: off


environment:
  global:
    STACK_ROOT: 'c:\sr'
    
  matrix:
    - platform: x86
      stackUrl: http://www.stackage.org/stack/windows-i386
      tarName: 'dist\win32-ia32.tar.gz'

    - platform: x64
      stackUrl: http://www.stackage.org/stack/windows-x86_64
      tarName: 'dist\win32-x64.tar.gz'


cache:
  - 'c:\sr'
  - 'C:\Users\appveyor\AppData\Local\Programs\stack'


before_test:
  # workaround for https://github.com/appveyor/ci/issues/1426
  - set PATH=%PATH%;C:\Program Files\Git\mingw64\bin
  - curl -sS -ostack.zip -L --insecure %stackUrl%
  - 7z x stack.zip stack.exe


clone_folder: 'c:\stack'


test_script:
  - "set PATH=%PATH%;c:\\stack"
  - stack setup > nil
  - stack path
  - stack build
  - mkdir -p dist
  - stack install --local-bin-path=dist


after_test:
  - 7z a -tgzip %tarName% 'dist\elm-instrument.exe'


artifacts:
  - path: "%tarName%"


deploy:
  - provider: GitHub
    artifact: "%tarName%"
    auth_token:
      secure: B76EIyeniWjavC3E7YcpwC61s0usacfLmWopYqNtKS8yleHjJVJ1J7lPJDWWzpAG
    draft: true
    on:
      branch: master

